title: XKNX
description: Control KNX devices with Python

theme: jekyll-theme-minimal


# Github repositories
github_user: XKNX
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
