title: XKNX
description: Control KNX devices with Python

theme: jekyll-theme-minimal

show_downloads: true

github:
    zip_url: "https://github.com/XKNX/xknx/archive/master.zip"
    tar_url: "https://github.com/XKNX/xknx/archive/master.tar.gz"
    repository_url: "http://github.com/XKNX/xknx"

# Github repositories
github_user: XKNX
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
